{% set name = "shared" %}
{% set version = "0.0.30" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/shared-{{ version }}.tar.gz
  sha256: 35ea8ad5d4e9ad229af0db3f9db103bcc1768049a4fdc4338b627bc934d3d437

build:
  entry_points:
    - shared = shared.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - paradict
    - python >=3.5

test:
  imports:
    - shared
  commands:
    - pip check
    - shared --help
  requires:
    - pip

about:
  home: https://github.com/pyrustic/shared
  summary: Data exchange and persistence
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
