{% set name = "shared" %}
{% set version = "0.0.31" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/shared-{{ version }}.tar.gz
  sha256: ab59785860d292919af7d6a71eb67792619f8568869ce8b4614a2acfb7f777d6

build:
  entry_points:
    - shared = shared.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - kvf
    - python >={{ python_min }}

test:
  imports:
    - shared
  commands:
    - pip check
    - shared --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/pyrustic/shared
  summary: Data exchange and persistence
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
