{% set name = "shared" %}
{% set version = "0.0.32" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/shared-{{ version }}.tar.gz
  sha256: 7308adc95c0dab14d0c99635cd8049d1f004cc7fef7396d3fe47323c34ec58c6

build:
  entry_points:
    - shared = shared.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - kvf
    - python >={{ python_min }}

test:
  imports:
    - shared
  commands:
    - pip check
    - shared --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/pyrustic/shared
  summary: Data exchange and persistence
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
