{% set name = "shared" %}
{% set version = "0.0.26" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/shared-{{ version }}.tar.gz
  sha256: a32af5a8c0b5e3d7f8ac7b6efce936e2c34b12c470c8645475232e3bbcf5ad66

build:
  entry_points:
    - shared = shared.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - jesth
    - python >=3.5

test:
  imports:
    - shared
  commands:
    - pip check
    - shared --help
  requires:
    - pip

about:
  home: https://github.com/pyrustic/shared
  summary: Data exchange and persistence
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
