{% set name = "shared" %}
{% set version = "0.0.29" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/shared-{{ version }}.tar.gz
  sha256: 6124b1c3ca0f4a328c78fecd59223d3259220fa4feb3effb6a3499356aab8862

build:
  entry_points:
    - shared = shared.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - jesth >=0.0.8  # Need this version but this pin not present upstream
    - python >=3.5

test:
  imports:
    - shared
  commands:
    - pip check
    - shared --help
  requires:
    - pip

about:
  home: https://github.com/pyrustic/shared
  summary: Data exchange and persistence
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
